<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeagueManager.Application\LeagueManager.Application.csproj" />
    <ProjectReference Include="..\LeagueManager.Infrastructure\LeagueManager.Infrastructure.csproj" />
    <ProjectReference Include="..\LeagueManager.Persistence\LeagueManager.Persistence.csproj" />
    <ProjectReference Include="..\LeagueManager.Presentation\LeagueManager.Presentation.csproj" />
  </ItemGroup>

</Project>
